substitutions:
  _BUCKET_NAME: ""  # You can override this from the trigger

steps:
  # Build Extract-to-GCS container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/extract-to-gcs'
      - '--file=./extract_to_gcs/Dockerfile'
      - './extract_to_gcs'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/extract-to-gcs']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - extract-to-gcs
      - '--image=gcr.io/$PROJECT_ID/extract-to-gcs'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,BUCKET_NAME=${_BUCKET_NAME}'

  # Build GCS-to-BigQuery container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcs-to-bigquery'
      - '--file=./gcs_to_bigquery/Dockerfile'
      - './gcs_to_bigquery'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcs-to-bigquery']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - gcs-to-bigquery
      - '--image=gcr.io/$PROJECT_ID/gcs-to-bigquery'
      - '--region=us-central1'
      - '--platform=managed'
      - '--no-allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID,BUCKET_NAME=${_BUCKET_NAME},DATASET_ID=$PROJECT_ID.university,TABLE_ID=$PROJECT_ID.university.amazon_scraped_data'

images:
  - 'gcr.io/$PROJECT_ID/extract-to-gcs'
  - 'gcr.io/$PROJECT_ID/gcs-to-bigquery'