substitutions:
  _BUCKET_NAME: ""

steps:
  # Build EL container (Extract and Load)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/extract-to-gcs', '--file=./extract_to_gcs/Dockerfile', './extract_to_gcs']

  # Push EL container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/extract-to-gcs']

  # Deploy EL to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'extract-to-gcs',
      '--image', 'gcr.io/$PROJECT_ID/extract-to-gcs',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'BUCKET_NAME=${_BUCKET_NAME}'
    ]

  # Build TL container (Transform and Load)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcs-to-bigquery', '--file=./gcs_to_bigquery/Dockerfile', './gcs_to_bigquery']

  # Push TL container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcs-to-bigquery']

  # Deploy TL to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'gcs-to-bigquery',
      '--image', 'gcr.io/$PROJECT_ID/gcs-to-bigquery',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--set-env-vars', 'BUCKET_NAME=${_BUCKET_NAME}'
    ]

images:
  - 'gcr.io/$PROJECT_ID/extract-to-gcs'
  - 'gcr.io/$PROJECT_ID/gcs-to-bigquery'