version: '3.9'

services:
  scraper:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./gcp/key.json:/secrets/key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/key.json